language: node_js

node_js:
  - node
  - 6

services:
  - postgresql
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
env:
  - CXX=g++-4.8

notifications:
  email: false

before_script:
  - psql -c 'create database dms_test;' -U postgres
  - npm run db:migrate:test

after_script:
  - npm run coveralls